name: Publish

on:
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  publish: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./TrixTutor.sln

      - name: Build
        run: dotnet build ./TrixTutor.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./TrixTutor.sln --configuration Release --no-build
